### Create session

POST /session

> {%
# Set-Cookie: sessionId=02d9953d8adde451899be54638820b8e  
%}


### Get chunks

GET /chunks
Cookie: sessionId=02d9953d8adde451899be54638820b8e
Content-Type: application/pdf


> {%
[
  {
    "id": "0ff0c836-529a-418f-8ffa-12538b5d5a55",
    "title": "Zasady dynamiki",
    "children": [
      {
        "id": "8e4807b7-f214-417c-9359-330be19149a0",
        "title": "I Zasada dynamiki",
      },
      {
        "id": "8e4807b7-f214-417c-9359-330be19149a0",
        "title": "II Zasada dynamiki",
      },
      {
        "id": "8e4807b7-f214-417c-9359-330be19149a0",
        "title": "III Zasada dynamiki",
      },
    ]
  },
  {
    "id": "0ff0c836-529a-418f-8ffa-12538b5d5a55",
    "title": "Termodynamika",
    "children": [
      // ...
    ]
  }
]
%}

### Evaluate summary

POST /chunk/{{chunkId}}/summary-evaluation
Cookie: sessionId=02d9953d8adde451899be54638820b8e 
Content-Type: application/json

{
  "summary": "Kiedy ciało bla bla..."
}

> {%
// Status 200
%}

> {%
// Status 400
{
  "hint": "Zapomniałeś o ..."
}
%}
