import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BookOpen } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import navLeft from "@/public/nav-left.png";
import navMid from "@/public/nav-mid.png";
import navRight from "@/public/nav-right.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col vc-init">
        <div className="flex flex-col h-screen">
          <nav className="flex flex-row h-20 justify-between w-screen shadow-sm">
            <Image src={navLeft} alt="" className="h-full w-auto" />
            <div className="flex">
              <Image src={navMid} alt="" className="h-full w-auto" />
              <Link
                href="/learn"
                className="flex flex-col content-center w-28 p-2 pt-3 cursor-pointer rounded-lg transition-all duration-200 hover:bg-gray-100 hover:scale-105 active:scale-95"
              >
                <BookOpen className="flex-1 w-full p-1 transition-transform duration-200 group-hover:rotate-3" />
                <span className="text-center">Learn</span>
              </Link>
            </div>
            <Image src={navRight} alt="" className="h-full w-auto" />
          </nav>
          <main className="flex-1 bg-white overflow-hidden">{children}</main>
        </div>
      </body>
    </html>
  );
}
